# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: lucio
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017