version: "3.1"

networks:
  node-rpg-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: node-rpg-postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=node-rpg
    ports:
      - "5432:5432"
    networks:
      - node-rpg-network

  db-test:
    image: postgres:latest
    container_name: node-rpg-postgres-test
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=node-rpg-test
    ports:
      - "5433:5432"
    networks:
      - node-rpg-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: node-rpg-rabbitmq
    hostname: my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=docker
      - RABBITMQ_DEFAULT_PASS=docker
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - node-rpg-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: node-rpg-swagger-ui
    environment:
      - SWAGGER_JSON=/app/swagger.yml
    volumes:
      - ./:/app
    ports:
      - "8080:8080"

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: node-rpg-swagger-editor
    environment:
      - SWAGGER_JSON=/app/swagger.yml
    volumes:
      - ./:/app
    ports:
      - "8081:8080"
